export const APPLIANCE_LIST_REQUEST = 'APPLIANCE_LIST_REQUEST'
export const APPLIANCE_LIST_SUCCESS = 'APPLIANCE_LIST_SUCCESS'
export const APPLIANCE_LIST_FAIL = 'APPLIANCE_LIST_FAIL'

export const APPLIANCE_DETAILS_REQUEST = 'APPLIANCE_DETAILS_REQUEST'
export const APPLIANCE_DETAILS_SUCCESS = 'APPLIANCE_DETAILS_SUCCESS'
export const APPLIANCE_DETAILS_FAIL = 'APPLIANCE_DETAILS_FAIL'


export const APPLIANCE_DELETE_REQUEST = 'APPLIANCE_DELETE_REQUEST'
export const APPLIANCE_DELETE_SUCCESS = 'APPLIANCE_DELETE_SUCCESS'
export const APPLIANCE_DELETE_FAIL = 'APPLIANCE_DELETE_FAIL'

export const APPLIANCE_CREATE_REQUEST = 'APPLIANCE_CREATE_REQUEST'
export const APPLIANCE_CREATE_SUCCESS = 'APPLIANCE_CREATE_SUCCESS'
export const APPLIANCE_CREATE_FAIL = 'APPLIANCE_CREATE_FAIL'
export const APPLIANCE_CREATE_RESET = 'APPLIANCE_CREATE_RESET'


export const APPLIANCE_UPDATE_REQUEST = 'APPLIANCE_UPDATE_REQUEST'
export const APPLIANCE_UPDATE_SUCCESS = 'APPLIANCE_UPDATE_SUCCESS'
export const APPLIANCE_UPDATE_FAIL = 'APPLIANCE_UPDATE_FAIL'
export const APPLIANCE_UPDATE_RESET = 'APPLIANCE_UPDATE_RESET'


export const APPLIANCE_CREATE_REVIEW_REQUEST = 'APPLIANCE_CREATE_REVIEW_REQUEST'
export const APPLIANCE_CREATE_REVIEW_SUCCESS = 'APPLIANCE_CREATE_REVIEW_SUCCESS'
export const APPLIANCE_CREATE_REVIEW_FAIL = 'APPLIANCE_CREATE_REVIEW_FAIL'
export const APPLIANCE_CREATE_REVIEW_RESET = 'APPLIANCE_CREATE_REVIEW_RESET'

export const APPLIANCE_TOP_REQUEST = 'APPLIANCE_TOP_REQUEST'
export const APPLIANCE_TOP_SUCCESS = 'APPLIANCE_TOP_SUCCESS'
export const APPLIANCE_TOP_FAIL = 'APPLIANCE_TOP_FAIL'