export const CLOTH_LIST_REQUEST = 'CLOTH_LIST_REQUEST'
export const CLOTH_LIST_SUCCESS = 'CLOTH_LIST_SUCCESS'
export const CLOTH_LIST_FAIL = 'CLOTH_LIST_FAIL'

export const CLOTH_DETAILS_REQUEST = 'CLOTH_DETAILS_REQUEST'
export const CLOTH_DETAILS_SUCCESS = 'CLOTH_DETAILS_SUCCESS'
export const CLOTH_DETAILS_FAIL = 'CLOTH_DETAILS_FAIL'


export const CLOTH_DELETE_REQUEST = 'CLOTH_DELETE_REQUEST'
export const CLOTH_DELETE_SUCCESS = 'CLOTH_DELETE_SUCCESS'
export const CLOTH_DELETE_FAIL = 'CLOTH_DELETE_FAIL'

export const CLOTH_CREATE_REQUEST = 'CLOTH_CREATE_REQUEST'
export const CLOTH_CREATE_SUCCESS = 'CLOTH_CREATE_SUCCESS'
export const CLOTH_CREATE_FAIL = 'CLOTH_CREATE_FAIL'
export const CLOTH_CREATE_RESET = 'CLOTH_CREATE_RESET'


export const CLOTH_UPDATE_REQUEST = 'CLOTH_UPDATE_REQUEST'
export const CLOTH_UPDATE_SUCCESS = 'CLOTH_UPDATE_SUCCESS'
export const CLOTH_UPDATE_FAIL = 'CLOTH_UPDATE_FAIL'
export const CLOTH_UPDATE_RESET = 'CLOTH_UPDATE_RESET'


export const CLOTH_CREATE_REVIEW_REQUEST = 'CLOTH_CREATE_REVIEW_REQUEST'
export const CLOTH_CREATE_REVIEW_SUCCESS = 'CLOTH_CREATE_REVIEW_SUCCESS'
export const CLOTH_CREATE_REVIEW_FAIL = 'CLOTH_CREATE_REVIEW_FAIL'
export const CLOTH_CREATE_REVIEW_RESET = 'CLOTH_CREATE_REVIEW_RESET'

export const CLOTH_TOP_REQUEST = 'CLOTH_TOP_REQUEST'
export const CLOTH_TOP_SUCCESS = 'CLOTH_TOP_SUCCESS'
export const CLOTH_TOP_FAIL = 'CLOTH_TOP_FAIL'