export const GROCERY_LIST_REQUEST = 'GROCERY_LIST_REQUEST'
export const GROCERY_LIST_SUCCESS = 'GROCERY_LIST_SUCCESS'
export const GROCERY_LIST_FAIL = 'GROCERY_LIST_FAIL'

export const GROCERY_DETAILS_REQUEST = 'GROCERY_DETAILS_REQUEST'
export const GROCERY_DETAILS_SUCCESS = 'GROCERY_DETAILS_SUCCESS'
export const GROCERY_DETAILS_FAIL = 'GROCERY_DETAILS_FAIL'


export const GROCERY_DELETE_REQUEST = 'GROCERY_DELETE_REQUEST'
export const GROCERY_DELETE_SUCCESS = 'GROCERY_DELETE_SUCCESS'
export const GROCERY_DELETE_FAIL = 'GROCERY_DELETE_FAIL'

export const GROCERY_CREATE_REQUEST = 'GROCERY_CREATE_REQUEST'
export const GROCERY_CREATE_SUCCESS = 'GROCERY_CREATE_SUCCESS'
export const GROCERY_CREATE_FAIL = 'GROCERY_CREATE_FAIL'
export const GROCERY_CREATE_RESET = 'GROCERY_CREATE_RESET'


export const GROCERY_UPDATE_REQUEST = 'GROCERY_UPDATE_REQUEST'
export const GROCERY_UPDATE_SUCCESS = 'GROCERY_UPDATE_SUCCESS'
export const GROCERY_UPDATE_FAIL = 'GROCERY_UPDATE_FAIL'
export const GROCERY_UPDATE_RESET = 'GROCERY_UPDATE_RESET'


export const GROCERY_CREATE_REVIEW_REQUEST = 'GROCERY_CREATE_REVIEW_REQUEST'
export const GROCERY_CREATE_REVIEW_SUCCESS = 'GROCERY_CREATE_REVIEW_SUCCESS'
export const GROCERY_CREATE_REVIEW_FAIL = 'GROCERY_CREATE_REVIEW_FAIL'
export const GROCERY_CREATE_REVIEW_RESET = 'GROCERY_CREATE_REVIEW_RESET'

export const GROCERY_TOP_REQUEST = 'GROCERY_TOP_REQUEST'
export const GROCERY_TOP_SUCCESS = 'GROCERY_TOP_SUCCESS'
export const GROCERY_TOP_FAIL = 'GROCERY_TOP_FAIL'