export const LAPTOP_LIST_REQUEST = 'LAPTOP_LIST_REQUEST'
export const LAPTOP_LIST_SUCCESS = 'LAPTOP_LIST_SUCCESS'
export const LAPTOP_LIST_FAIL = 'LAPTOP_LIST_FAIL'

export const LAPTOP_DETAILS_REQUEST = 'LAPTOP_DETAILS_REQUEST'
export const LAPTOP_DETAILS_SUCCESS = 'LAPTOP_DETAILS_SUCCESS'
export const LAPTOP_DETAILS_FAIL = 'LAPTOP_DETAILS_FAIL'


export const LAPTOP_DELETE_REQUEST = 'LAPTOP_DELETE_REQUEST'
export const LAPTOP_DELETE_SUCCESS = 'LAPTOP_DELETE_SUCCESS'
export const LAPTOP_DELETE_FAIL = 'LAPTOP_DELETE_FAIL'

export const LAPTOP_CREATE_REQUEST = 'LAPTOP_CREATE_REQUEST'
export const LAPTOP_CREATE_SUCCESS = 'LAPTOP_CREATE_SUCCESS'
export const LAPTOP_CREATE_FAIL = 'LAPTOP_CREATE_FAIL'
export const LAPTOP_CREATE_RESET = 'LAPTOP_CREATE_RESET'


export const LAPTOP_UPDATE_REQUEST = 'LAPTOP_UPDATE_REQUEST'
export const LAPTOP_UPDATE_SUCCESS = 'LAPTOP_UPDATE_SUCCESS'
export const LAPTOP_UPDATE_FAIL = 'LAPTOP_UPDATE_FAIL'
export const LAPTOP_UPDATE_RESET = 'LAPTOP_UPDATE_RESET'


export const LAPTOP_CREATE_REVIEW_REQUEST = 'LAPTOP_CREATE_REVIEW_REQUEST'
export const LAPTOP_CREATE_REVIEW_SUCCESS = 'LAPTOP_CREATE_REVIEW_SUCCESS'
export const LAPTOP_CREATE_REVIEW_FAIL = 'LAPTOP_CREATE_REVIEW_FAIL'
export const LAPTOP_CREATE_REVIEW_RESET = 'LAPTOP_CREATE_REVIEW_RESET'

export const LAPTOP_TOP_REQUEST = 'LAPTOP_TOP_REQUEST'
export const LAPTOP_TOP_SUCCESS = 'LAPTOP_TOP_SUCCESS'
export const LAPTOP_TOP_FAIL = 'LAPTOP_TOP_FAIL'