export const MOBILE_LIST_REQUEST = 'MOBILE_LIST_REQUEST'
export const MOBILE_LIST_SUCCESS = 'MOBILE_LIST_SUCCESS'
export const MOBILE_LIST_FAIL = 'MOBILE_LIST_FAIL'

export const MOBILE_DETAILS_REQUEST = 'MOBILE_DETAILS_REQUEST'
export const MOBILE_DETAILS_SUCCESS = 'MOBILE_DETAILS_SUCCESS'
export const MOBILE_DETAILS_FAIL = 'MOBILE_DETAILS_FAIL'


export const MOBILE_DELETE_REQUEST = 'MOBILE_DELETE_REQUEST'
export const MOBILE_DELETE_SUCCESS = 'MOBILE_DELETE_SUCCESS'
export const MOBILE_DELETE_FAIL = 'MOBILE_DELETE_FAIL'

export const MOBILE_CREATE_REQUEST = 'MOBILE_CREATE_REQUEST'
export const MOBILE_CREATE_SUCCESS = 'MOBILE_CREATE_SUCCESS'
export const MOBILE_CREATE_FAIL = 'MOBILE_CREATE_FAIL'
export const MOBILE_CREATE_RESET = 'MOBILE_CREATE_RESET'


export const MOBILE_UPDATE_REQUEST = 'MOBILE_UPDATE_REQUEST'
export const MOBILE_UPDATE_SUCCESS = 'MOBILE_UPDATE_SUCCESS'
export const MOBILE_UPDATE_FAIL = 'MOBILE_UPDATE_FAIL'
export const MOBILE_UPDATE_RESET = 'MOBILE_UPDATE_RESET'


export const MOBILE_CREATE_REVIEW_REQUEST = 'MOBILE_CREATE_REVIEW_REQUEST'
export const MOBILE_CREATE_REVIEW_SUCCESS = 'MOBILE_CREATE_REVIEW_SUCCESS'
export const MOBILE_CREATE_REVIEW_FAIL = 'MOBILE_CREATE_REVIEW_FAIL'
export const MOBILE_CREATE_REVIEW_RESET = 'MOBILE_CREATE_REVIEW_RESET'

export const MOBILE_TOP_REQUEST = 'MOBILE_TOP_REQUEST'
export const MOBILE_TOP_SUCCESS = 'MOBILE_TOP_SUCCESS'
export const MOBILE_TOP_FAIL = 'MOBILE_TOP_FAIL'