# Generated by Django 3.2.7 on 2021-11-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211114_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='appliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.appliances'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cloth'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='furniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.furniture'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='grocery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.grocery'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='laptop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.laptop'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.mobile'),
        ),
    ]
