# Generated by Django 3.2.7 on 2021-11-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211121_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='appliance',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cloth',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='laptop',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='mobile',
        ),
    ]
