# Generated by Django 3.2.7 on 2021-11-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211121_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='comment',
        ),
    ]
