# Generated by Django 3.2.7 on 2021-11-22 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_review_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcloth',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewcloth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewfurniture',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewfurniture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewgrocery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewgrocery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewlaptop',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewlaptop',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewmobile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewmobile',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='appliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.appliances'),
        ),
        migrations.AddField(
            model_name='review',
            name='cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cloth'),
        ),
        migrations.AddField(
            model_name='review',
            name='furniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.furniture'),
        ),
        migrations.AddField(
            model_name='review',
            name='grocery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.grocery'),
        ),
        migrations.AddField(
            model_name='review',
            name='laptop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.laptop'),
        ),
        migrations.DeleteModel(
            name='ReviewAppliance',
        ),
        migrations.DeleteModel(
            name='ReviewCloth',
        ),
        migrations.DeleteModel(
            name='ReviewFurniture',
        ),
        migrations.DeleteModel(
            name='ReviewGrocery',
        ),
        migrations.DeleteModel(
            name='ReviewLaptop',
        ),
        migrations.DeleteModel(
            name='ReviewMobile',
        ),
    ]
