# Generated by Django 3.2.7 on 2021-11-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211122_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='product',
        ),
    ]
