# Generated by Django 3.2.7 on 2021-11-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
