# Generated by Django 3.2.7 on 2021-11-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_contactform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
