appliances = [
    {
        '_id': '1',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/airpods.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 2.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image':'/img/alexa.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,
    },
    {
        '_id': '3',
        'name': 'Detol Handwash',
        'image': '/img/mouse.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '4',
        'name': 'Detol Handwash',
        'image': '/img/camera.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '5',
        'name': 'Sofaset',
        'image': '/img/playstation.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '6',
        'name': 'Sofaset',
        'image': '/img/laptop5.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '7',
        'name': 'Detol Handwash',
        'image': '/img/laptop5.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '8',
        'name': 'Fantasy T-shirt',
        'image': '/img/laptop5.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '9',
        'name': 'Fantasy T-shirt',
        'image': '/img/laptop5.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '10',
        'name': 'Fantasy T-shirt',
        'image': '/img/laptop5.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '11',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/laptop5.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '12',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/laptop5.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
]