clothes = [
    {
        '_id': '1',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth1.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '2',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth2.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '3',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth3.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '4',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth4.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '5',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth5.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '6',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth6.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '7',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth7.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '8',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth8.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '9',
        'name': 'Fantasy T-shirt',
        'image': '/img/cloth9.jpg',
        'description':'A T-shirt, or tee shirt, is a style of fabric shirt named after the T shape of its body and sleeves',
        'brand': 'Puma',
        'category': 'Clothes',
        'price': 498.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
]