furnitures = [
    {
        '_id': '1',
        'name': 'Sofaset',
        'image': '/img/fur1.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '2',
        'name': 'Sofaset',
        'image': '/img/fur2.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '3',
        'name': 'Sofaset',
        'image': '/img/fur3.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '4',
        'name': 'Sofaset',
        'image': '/img/fur4.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '5',
        'name': 'Sofaset',
        'image': '/img/fur5.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '6',
        'name': 'Sofaset',
        'image': '/img/fur6.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '7',
        'name': 'Sofaset',
        'image': '/img/fur7.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '8',
        'name': 'Sofaset',
        'image': '/img/fur8.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '9',
        'name': 'Sofaset',
        'image': '/img/fur9.jpg',
        'description':'Home Centre Signature Arden Fabric Ar ml.ess Sofa -1 Seater Brown',
        'brand': 'ARden',
        'category': 'Furnitures',
        'price': 23000.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
]