grocerys = [
    {
        '_id': '1',
        'name': 'Detol Handwash',
        'image': '/img/gro1.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '2',
        'name': 'Detol Handwash',
        'image': '/img/gro2.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '3',
        'name': 'Detol Handwash',
        'image': '/img/gro3.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '4',
        'name': 'Detol Handwash',
        'image': '/img/gro4.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '5',
        'name': 'Detol Handwash',
        'image': '/img/gro5.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '6',
        'name': 'Detol Handwash',
        'image': '/img/gro6.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '7',
        'name': 'Detol Handwash',
        'image': '/img/gro7.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '8',
        'name': 'Detol Handwash',
        'image': '/img/gro8.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
    {
        '_id': '9',
        'name': 'Detol Handwash',
        'image': '/img/gro9.jpg',
        'description':'handwash',
        'brand': 'Detol',
        'category': 'grocery',
        'price': 70.0,
        'countInStock': 5,
        'rating': 4,
        'numReviews': 18,
    },
]