laptops = [
    {
        '_id': '1',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop1.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '2',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop2.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '3',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image':'/img/laptop3.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '4',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop4.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '5',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image':'/img/laptop5.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '6',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop6.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '7',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop7.png',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '8',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop8.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
    {
        '_id': '9',
        'name': 'Lenovo IdeaPad 3 Core i3 10th Gen',
        'image': '/img/laptop9.jpg',
        'description':'(8 GB/256 GB SSD/Windows 10 Home) 15IML05 Thin and Light Laptop (15.6 Inch, Platinum Grey, 1.7 kg, With MS Office)',
        'brand': 'Lenovo',
        'category': 'Laptops',
        'price': 480699.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 20,           
    },
]