mobiles = [
    {
    '_id': '1',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/mobile1.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/mobile2.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '3',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/mobile3.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/mobile4.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'realme C21Y (Cross Black)',
        'image':'/img/mobile5.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '6',
        'name': 'realme C21Y (Cross Black)',
        'image':'/img/mobile6.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '7',
        'name': 'realme C21Y (Cross Black)',
        'image':'/img/mobile7.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '8',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/mob1.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '9',
        'name': 'realme C21Y (Cross Black)',
        'image': '/img/mob2.jpg',
        'description':
        '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB 16.51 cm (6.5 inch) HD+ Display 5000 mAh Battery 13MP + 2MP + 2MP | 5MP Front Camera',
        'brand': 'Poco',
        'category': 'Electronics',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
]